name: landmark-recognition
channels:
  - pytorch
dependencies:
  - scikit-learn
  - pandas
  - pillow
  - absl-py
  - ignite
  - pytorch
  - torchvision
  - tqdm
  - conda-forge::tensorboardx<1.7
  - conda-forge::pyflann
