name: landmark-recognition
channels:
  - pytorch
dependencies:
  - pylint
  - jedi
  - scipy
  - jupyter
  - pillow
  - scikit-learn
  - pandas
  - absl-py
  - ignite
  - pytorch
  - torchvision
  - tqdm
  - conda-forge::tensorboardx<1.7
  - conda-forge::pyflann
  - pip
  - pip:
    - pytorch-lightning
    - tensorboard
    - tensorflow
    - efficientnet-pytorch
