name: landmark-recognition
channels:
  - pytorch
dependencies:
  - jupyter
  - pillow
  - scikit-learn
  - pandas
  - absl-py
  - ignite
  - pytorch
  - torchvision
  - tqdm
  - conda-forge::tensorboardx<1.7
  - pip
  - pip:
    - "--extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali"
    - tensorboard
    - tensorflow
